// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
  aws_app_analytics: 'enable',
  aws_cognito_identity_pool_id: 'us-east-1:31c81abc-8f74-42a7-ab52-5dac5f9cfa07',
  aws_cognito_region: 'us-east-1',
  aws_content_delivery: 'enable',
  aws_content_delivery_bucket: 'awsamplifyvue-hosting-mobilehub-1216106526',
  aws_content_delivery_bucket_region: 'us-east-1',
  aws_content_delivery_cloudfront: 'enable',
  aws_content_delivery_cloudfront_domain: 'd3umnd46oo5yqg.cloudfront.net',
  aws_mobile_analytics_app_id: '40707047cbed44c1834f465dc9894b69',
  aws_mobile_analytics_app_region: 'us-east-1',
  aws_project_id: '75fd8014-47d9-4d94-b363-e9903b73f644',
  aws_project_name: 'aws-amplify-vue',
  aws_project_region: 'us-east-1',
  aws_resource_name_prefix: 'awsamplifyvue-mobilehub-1216106526',
  aws_sign_in_enabled: 'enable',
  aws_user_files: 'enable',
  aws_user_files_s3_bucket: 'awsamplifyvue-userfiles-mobilehub-1216106526',
  aws_user_files_s3_bucket_region: 'us-east-1',
  aws_user_pools: 'enable',
  aws_user_pools_id: 'us-east-1_NqlWmD3bp',
  aws_user_pools_mfa_type: 'ON',
  aws_user_pools_web_client_id: '685qnqh3vjiuok3j7mg2tp047t',
};

export default awsmobile;
